version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/sdm:/opt/musicas
            - /var/log/liquidsoap.log:/var/log/liquidsoap.log
        restart: unless-stopped

    php:
        container_name: php
        image: php:fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/single-lemp/
            dockerfile: php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/php/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/sdm:/opt/musicas
            - /var/log/liquidsoap.log:/var/log/liquidsoap.log
        restart: unless-stopped
