version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/github:/code
            - ~/docker/confs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/confs/nginx/snippets:/etc/nginx/snippets
            - ~/docker/certs:/etc/ssl/nginx
        restart: unless-stopped

    php:
        container_name: php
        image: php:fpm
        depends_on:
            - nginx
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/lemp/
            dockerfile: php
        volumes:
            - ~/github:/code
            - ~/docker/confs/php/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/docker/confs/php/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        restart: unless-stopped

    nginxalt:
        container_name: nginxalt
        image: nginx:latest
        ports:
            - "8080:8080"
            - "8843:8843"
        volumes:
            - ~/sites:/code
            - ~/docker/confs/nginx/nginxalt.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/confs/nginx/snippets:/etc/nginx/snippets
            - ~/docker/certs:/etc/ssl/nginx
        restart: unless-stopped

    phpalt:
        container_name: phpalt
        image: php:fpm
        depends_on:
            - nginxalt
        ports:
            - "9090:9090"
        build:
            context: ../../dockerfile/lemp/
            dockerfile: phpalt
        volumes:
            - ~/sites:/code
            - ~/docker/confs/php/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/docker/confs/php/fpm2.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        restart: unless-stopped

    mysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        build:
            context: ../../dockerfile/lemp/
            dockerfile: mysql
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        restart: unless-stopped

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        volumes:
            - ~/docker/confs/phpmyadmin/phpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
        restart: unless-stopped

    adminer:
        container_name: adminer
        image: adminer:latest
        ports:
            - 8090:8080
        restart: unless-stopped
