# Inserts a blank line between shell prompts
add_newline = false

#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$username@$hostname $directory$rust$package
#[â””â”€>](bold green) $status"""

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = ".../"
read_only = " ğŸ”’"

[cmd_duration]
min_time = 500
format = "DuraÃ§Ã£o [$duration](bold yellow)"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
